name: Run deployment

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_deployment]

env:
  IMAGE_NAME: ghcr.io/tklein1801/d2pb

jobs:
  renew_docker_compose:
    name: Rebuild Remote Docker-Compose
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker container stop dulli-bot
            docker container rm dulli-bot
            docker image rm ${{env.IMAGE_NAME}}:latest
            docker pull ${{env.IMAGE_NAME}}:${{ github.ref_name }}
            docker tag ${{env.IMAGE_NAME}}:${{ github.ref_name }} ${{env.IMAGE_NAME}}:latest
            docker run -itd --env-file '/home/dulliag/dullibot.env' --restart on-failure:3 --name=dulli-bot ${{env.IMAGE_NAME}}:latest
