name: Run deployment

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_deployment]

env:
  IMAGE_NAME: ghcr.io/dulliag/infoapp-notifications

jobs:
  renew_docker_compose:
    name: Rebuild Remote Docker-Compose
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker stop a3pli-notifications || true
            docker rm a3pli-notifications || true
            docker image rm ${{env.IMAGE_NAME}}:latest || true
            docker pull ${{env.IMAGE_NAME}}:latest
            docker run -itd --env-file '/home/dulliag/a3pli.env' --restart on-failure:3 --name=a3pli-notifications ${{env.IMAGE_NAME}}:latest
